name: Ping app to avoid sleeping

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        run: curl -m 60 https://appregresion.onrender.com
