name: Ping app to avoid sleeping

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app with headers
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            https://appregresion.onrender.com
